POST http://localhost:8000/auth/signup HTTP/1.1
content-type: application/json

{
    "firstName": "Joan",
    "lastName": "Doe",
    "email": "abc@123456.de",
    "password": "password123ab!@#"
}

###

GET http://localhost:8000 HTTP/1.1
###

POST http://localhost:8000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "abc@123.de",
    "password": "password123ab!@#"
}

###

PATCH http://localhost:8000/user/29edef1c-f3cc-4bb0-a1c6-af4a83a1726a HTTP/1.1
Content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI5ZWRlZjFjLWYzY2MtNGJiMC1hMWM2LWFmNGE4M2ExNzI2YSIsImlhdCI6MTY4OTc1ODczNn0.3vl085JI1czudzP8f-8eiT8xfb7fPjZjGbOQ_PRecKY

{
    "firstName": "Steven",
    "lastName": "Bark"
}
