POST http://localhost:8000/screening HTTP/1.1
Content-type: application/json

[{
    "movieId": 976573,
    "datetime": "{{$localDatetime iso8601}}",
    "seatAvailability": [
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0]
},{
    "movieId": 502356,
    "datetime": "{{$localDatetime iso8601}}",
    "seatAvailability": [
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0]
}]

###
GET http://localhost:8000/screening/?movieId=807172 HTTP/1.1


###
GET http://localhost:8000/screening/?movieId=807172&date=2023-07-26 HTTP/1.1


###

DELETE http://localhost:8000/screening HTTP/1.1